parameters:
  - name: ref
    type: string
    default: main

trigger: none

pool: ipam-devops

resources:
  repositories:
    - repository: postman
      type: github
      name: leriksen/postman
      ref: ${{ parameters.ref }}
      endpoint: github.com_leriksen

stages:
  - stage: newman
    displayName: Run Newman
    jobs:
      - job: newman
        displayName: Run Newman
        workspace:
          clean: all
        steps:
          - checkout: postman

          - script: newman --version
            displayName: Show newman version

          - task: AzureCLI@2
            displayName: Run newman
            inputs:
              azureSubscription: default
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                newman run as-env.postman_collection.json -e default.postman_environment.json -r 'cli,junitfull' --reporter-junitfull-export junit.xml --verbose

          - task: PublishTestResults@2
            displayName: Publish JUnit results
            inputs:
              testResultsFormat: JUnit
              testResultsFiles: junit.xml