parameters:
  - name: ref
    type: string
    default: main

trigger: none

pool: ipam-devops

repositories:
  - repository: postman
    type: github
    name: leriksen/postman
    ref: $(ref)
    endpoint: github.com_leriksen

stages:
  - stage: newman
    displayName: Run Newman
    jobs:
      - job: newman
        displayName: Run Newman
        workspace:
          clean: all
        steps:
          - checkout: postman